### ISSUE TITLE
Loosen (or bump) dependency on rubocop?

### ISSUE THREAD

**Issue by utkarsh2102** [pat/combustion#104]
Hi @pat,

Thanks for your awesome work on this so far.
https://github.com/pat/combustion/blob/309e9f7c69325d1a209727823e9c7ca6d75cdf5b/combustion.gemspec#L30

Whilst maintaining this library in Debian, it fails to build since the version in the Debian archive is 0.80.1. We'd need to patch this, can this be done here, too?

Also, irrespective of this, can you please make a new release, too? :)

**Comment by pat** [comment]
Just updated and relaxed the dependency, and published v1.2.0 :) Thanks for the prod!

**Comment by utkarsh2102** [comment]
You're awesome! ❤️
