### ISSUE TITLE
Drop `git` in gemspec?

### ISSUE THREAD

**Issue by utkarsh2102** [pat/combustion#109]
Hi @pat,

Thanks for your awesome work on maintaining this library! ❤️ 
However, while maintaining this in Debian, we found that this library uses on `git ls-files` to produce a list of files.

Using git is a bit problematic for us, more explanation at here: https://packaging.rubystyle.guide/#gemspec-git

I am happy to raise a PR in case you agree to have this fixed? 😄

**Comment by pat** [comment]
Hi Utkarsh - and sorry for taking a while to respond to your message!

To be honest, part of what's made me pause is that while I agree that relying on git for the gemspec is a habit I should get out of, removing git makes it easier to bundle up files that I hadn't meant to release (i.e. that I hadn't committed - experiments, in-progress features, etc).

But at the end of the day, I think your suggestion is the right one. If you've still got time to figure out a PR, that'd be appreciated! If not, no worries, I can look into it soon.
