### ISSUE TITLE
Rails edge failure involving sprockets-rails

### ISSUE THREAD

**Issue by jrochkind** [pat/combustion#119]
Hi, I use combustion to test on multiple rails versions, including "edge" from `main` branch in Rails repo. So I notice quick when something breaks!

Up to you whether you want to support rails-edge or not, I'm just letting you know! You can treat it as a preview of what you'll eventually probably have to do for the next Rails pre-release, or an eventual Rails 7 final release. 

Rails main branch no longer includes sprockets-rails as a dependency. Which means a `Combustion.initialize! :all` will raise `LoadError:  cannot load such file -- sprockets/railtie` on this line:

https://github.com/pat/combustion/blob/40d5fd3c3e84e331d1b55b3bf1d306dcca33ae03/lib/combustion.rb#L24

Why doesn't Rails include sprockets-rails as a dependency?  It means to make sprockets use optional, suggesting a new Gem as an alternative. See:

* https://github.com/rails/rails/pull/43261
* https://github.com/rails/rails/commit/fb1ab3460a676ce7def0819c2e92289ef2dcbe3b

Workaround for use with present Combustion?

* Just add an explicit `gem "sprockets-rails"` to your dependencies; if you're using Appraisal (as I am), to the specific appraisal block for rails-edge
* OR, if you don't actually use sprockets, you could not do `Combustion.initialize.all!`, but explicitly list out the things you want, not including sprockets. 

What should Combustion do for the long-run?

* Not sure, maybe it needs to only conditionally require sprockets if `defined?(Sprockets)`, but the existing codebase makes that hard without a refactor. 
* Or... not try to initialize/require sprockets by default with Rails 7?  But many Rails 7 projects will still want sprockets, and it needs to be easy and clearly documented how to get it. Not sure.

**Comment by pat** [comment]
Thanks for this report @jrochkind - sorry it took me a while to respond to both this and #120.

I've opted for your final option: Sprockets is no longer loaded by default when testing against Rails 7, and there's a note in the README. Thanks for doing all the research and making suggestions on how to resolve it, greatly appreciated! Fixes for both the issues are part of Combustion v1.3.4 :)
