### ISSUE TITLE
ActiveRecord::Base.clear_active_connections! is deprecated in current edge Rails 7.1

### ISSUE THREAD

**Issue by jrochkind** [pat/combustion#130]
No rush, but eventually we'll want to deal with this, combustion is triggering deprecation warning in current edge Rails 7.1 

> DEPRECATION WARNING: Calling `ActiveRecord::Base.clear_active_connections!` is deprecated. Please call the method directly on the connection handler; for example: `ActiveRecord::Base.connection_handler.clear_active_connections!`. (called from reset at combustion-8916f6bec7f1/lib/combustion/databases/postgresql.rb:5)

**Comment by pat** [comment]
Just resolved this with c1bc7dadc498c970cc24f4630dda6fe4add3e6aa - and then removed MRI 2.4 and 2.5 from the test matrix, and added in 3.2 :)
