### ISSUE TITLE
deprecation warning in Rails 7.1 on clear_active_connections!

### ISSUE THREAD

**Issue by jrochkind** [pat/combustion#132]
Rails: 7.1.1
Combustion: 1.3.7

> DEPRECATION WARNING: Calling `ActiveRecord::Base.clear_active_connections!` is deprecated. Please call the method directly on the connection handler; for example: `ActiveRecord::Base.connection_handler.clear_active_connections!`

Triggered by `Combustion.initialize! :all`

**Comment by ankane** [comment]
Hi @jrochkind, this was fixed in c1bc7dadc498c970cc24f4630dda6fe4add3e6aa (but hasn't been released).

**Comment by jrochkind** [comment]
Thanks!  Any plans for a release?

**Comment by pat** [comment]
As noted in #133, new release is finally out 😅
