### ISSUE TITLE
deprecation warning on Rails 7.1 on config.active_support.cache_format_version = 6.1

### ISSUE THREAD

**Issue by jrochkind** [pat/combustion#133]
Rails: 7.1.1
Combustion: 1.3.7

> DEPRECATION WARNING: Support for `config.active_support.cache_format_version = 6.1` has been deprecated and will be removed in Rails 7.2.
>
> Check the Rails upgrade guide at https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#new-activesupport-cache-serialization-format for more information on how to upgrade.

on `Combustion.initialize! :all`

**Comment by ankane** [comment]
Hi @jrochkind, this was fixed in #131 (but hasn't been released).

**Comment by jrochkind** [comment]
@ankane @pat Thanks!  Are y'all interested in a combustion release anytime soon?

It looks like the last release was 1.3.7 in June 2022 (~18 months ago)

I'd love to get a release that includes all these fixes for 7.1 deprecation warnings, such #131  and also c1bc7dad

Thank you!

**Comment by pat** [comment]
Sorry for the delay, finally got a new release out! (1.4.0)

Here's hoping I'm a bit better at keeping up with OSS things this year 😅

**Comment by jrochkind** [comment]
thanks @pat!
