### ISSUE TITLE
new version 0.5.4?

### ISSUE THREAD

**Issue by artofhuman** [pat/combustion#69]
Hello @pat 
Can you release new version with this fix https://github.com/pat/combustion/pull/65 ?

**Comment by sergey-kucher** [comment]
+1

**Comment by deniskorobicyn** [comment]
:+1:,  getting tied of writing separate dependency for this gem in Gemfile, instead of `development_dependency` in gemspec. Please, @pat, can you release version? :smile:

**Comment by pat** [comment]
Sorry for the delays - meant to get to this over the break, but ended up having very little coding time. 0.5.4 is now released!

**Comment by deniskorobicyn** [comment]
Thank you!! :heart:

**Comment by artofhuman** [comment]
Thanks :+1:
