### ISSUE TITLE
0.5.5 has changed API

### ISSUE THREAD

**Issue by krzysiek1507** [pat/combustion#75]
Patch update shouldn't change API.

**Comment by pat** [comment]
I appreciate your concern, but everything within `Combustion::Database.setup` is internal implementation - the calls within that are not documented anywhere, and weren't built with re-use in mind. Even `Combustion::Database.setup` itself is only used internally.

Do you have code that is using the old methods of `Combustion::Database`? I'm curious as to how people may be using Combustion beyond what's documented.
