### ISSUE TITLE
Support for Minitest?

### ISSUE THREAD

**Issue by ericpeters0n** [pat/combustion#78]
yes/no/maybe/already?

**Comment by pat** [comment]
I've not used Combustion with Minitest, nor does anything within it exist specifically for that purpose, but patches are very much welcome. It was discussed briefly in #4, but nothing detailed.

**Comment by ericpeters0n** [comment]
Thanks for the reply. I’ll poke at it to explore feasibility and effort when I get a chance! :)

**Comment by jmervine** [comment]
FWIW, I was able to use this with Minitest by creating a `test/test_helper.rb` file, which I required in each of my tests files...

```ruby
#file: test/test_helper.rb
require "combustion"
Combustion.path = "test/internal"
Combustion.initialize! :all
```

**Comment by pat** [comment]
Thanks for sharing that Joshua, great to hear it's working for you :)

**Comment by fschwahn** [comment]
I did exactly the same, also works flawlessly. I'm doing integration tests, however I'm not using activerecord.
