### ISSUE TITLE
uninitialized constant Combustion::Bundler

### ISSUE THREAD

**Issue by anson2590** [pat/combustion#81]
Hi,
Im using combusion version 0.7.0 gem and rails version 5.1. , when i try to run rspec I get error saying.
Failure/Error:
  Combustion.initialize! :action_controller do
    config.cache_store = :null_store
  end

NameError:
  uninitialized constant Combustion::Bundler

Can someone explain what the issue might be and how to resolve it.

**Comment by pat** [comment]
Hi 👋 

It sounds like you're not loading Bundler before you're loading Combustion? I don't suppose you can spare the `spec_helper.rb` file for your project? Or even better, is the project open-source and online so I can review it directly?

**Comment by anson2590** [comment]
Hi, 
Thanks pat, now it is working i had bug in my code, fixed it.

**Comment by pat** [comment]
Oh great, good to know you figured it out :) Any further issues, do let me know!
