### ISSUE TITLE
"No such file - ["config/database.yml"]" (not a rails engine)

### ISSUE THREAD

**Issue by jrochkind** [pat/combustion#85]
I have a gem which isn't actually a Rails::Engine (it has no Rails::Engine in it), which could be the root of the problem. My gem doesn't need any of the features that come with Rails::Engine, but it _is_ meant for use with Rails (and does depend on ActiveRecord), and I want to have some integration tests in rspec to verify it works as expected in the context of Rails.  So combustion seems very useful. 

Not sure if not being a Rails::Engine is part of the problem or not.  I have a bunch of specs that were already running fine, including many ActiveRecord. Now I want to add some integration tests. 

My `spec_helper.rb`, trying to get the simplest thing that might work working, has:

```ruby
require 'bundler'
Bundler.require :default, :development
Combustion.initialize! :active_record
```

From the `Combustion.initialize!` line, I get an exception raised: 

```
RuntimeError: Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]
 ```

[full stack trace](https://gist.github.com/jrochkind/55fe26499cc32cd4df3ce995f573cebd)

I _have_ run `bundle exec combust`, and _do_ have the files at `spec/internal`, including `spec/internal/config/database.yml`

Any ideas or hints of what might be going on, or where I should go next? Thanks!

**Comment by jrochkind** [comment]
Aha. I had [standalone_migrations](https://github.com/thuss/standalone-migrations) in my app, from before I considered using combustion. 

They are incompatible in some way. Removing standalone-migrations, the error goes away, and my tests are running (although oddly having some failures they didn't have before, even before actually adding the integration test!  Due to some differences in environment between combustion vs just `require 'activerecord'` I guess. But this I can explore!)

So nevermind, closing! Good to know it is incompatible with standalone_migrations (and indeed there's probably no good reason to use both).

**Comment by pat** [comment]
Great to know you've got things working :) Certainly if you hit other problems you're unsure about, feel free to open further issues here!

**Comment by jrochkind** [comment]
@pat thanks! I've got it working, but did have some confusions and things I'm still not certain about. Would it make sense for me to open an issue for each individually?
