### ISSUE TITLE
Maybe release? Rails 6 is broken(

### ISSUE THREAD

**Issue by palkan** [pat/combustion#96]
Rails 6 is not working with the latest release (AR configuration changes), but works fine with the lates master (thanks to this commit 
https://github.com/pat/combustion/commit/3c4bc97e0ff7870c1589bcdbc1c41b3966932eb6).

Any plans to release it?

P.S. Thanks for the great gem)

**Comment by pat** [comment]
Just released v1.1.0 which includes the Rails 6 fix :)
